version: '3.3'

services:
  api:
    build: ./api
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development

  web-app:
    build: ./web-app
    restart: always
    depends_on:
      - api
    volumes:
      - ./web-app:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development

  message-consumer:
    build: ./message-consumer
    restart: always
    depends_on:
      - redis
    volumes:
      - ./message-consumer:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      ADAPTER: 'FAUX'
      FROM_MOBILE: '+447000000000'

  postgres:
    image: postgres:9.3.22-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=table-queue
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "2000:2000"
    depends_on:
      - api
      - web-app
      - pgadmin

  redis:
    image: redis:3.2.11-alpine
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@local
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "8080:80"
