version: '3.3'

services:
  api:
    build: ./api
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development

  app:
    build: ./app
    restart: always
    depends_on:
      - api
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development

  postgres:
    image: postgres:9.3.22-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=table-queue
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "2000:2000"
    depends_on:
      - api
      - app
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@local
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "8080:80"
