version: '3.3'

services:
  api:
    build: ./api
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

  postgres:
    image: postgres:9.3.22-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=table-queue
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@local
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/pgadmin/
