export const FETCH_RESTAURANT = 'FETCH_RESTAURANT';
export const FETCH_RESTAURANT_REQUEST = 'FETCH_RESTAURANT_REQUEST';
export const FETCH_RESTAURANT_SUCCESS = 'FETCH_RESTAURANT_SUCCESS';
export const FETCH_RESTAURANT_FAILURE = 'FETCH_RESTAURANT_FAILURE';

export const FETCH_RESTAURANT_BY_INDICATOR = 'FETCH_RESTAURANT_BY_INDICATOR';
export const FETCH_RESTAURANT_BY_INDICATOR_REQUEST = 'FETCH_RESTAURANT_BY_INDICATOR_REQUEST';
export const FETCH_RESTAURANT_BY_INDICATOR_SUCCESS = 'FETCH_RESTAURANT_BY_INDICATOR_SUCCESS';
export const FETCH_RESTAURANT_BY_INDICATOR_FAILURE = 'FETCH_RESTAURANT_BY_INDICATOR_FAILURE';

export const CREATE_RESERVATION = 'CREATE_RESERVATION';
export const CREATE_RESERVATION_REQUEST = 'CREATE_RESERVATION_REQUEST';
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS';
export const CREATE_RESERVATION_FAILURE = 'CREATE_RESERVATION_FAILURE';
